### PR TITLE
Fix placement of version column to  be after time_value

### PR DESCRIPTION
**Pull request by XuedaShen**

### CODE REVIEW

**Comment by dajmcdon** [comment]
@XuedaShen Is this "ready to go" or are you still working? 

1. If ready, please resolve the conflicts in the `*.qmd` files (the others are derived from those, and will get overwritten, so you can take care of that however).
2. Tag me for Review.

**Comment by XuedaShen** [comment]
Hi Dan, this is not quite ready. I will tag you when I resolve the conflicts.

**Comment by XuedaShen** [comment]
@dajmcdon I am going to close this PR; it seems the slide I originally referred to is no longer there and I didn't manage my branch too carefully. Sorry!

**Comment by XuedaShen** [comment]
@dajmcdon I am going to close this PR; it seems the slide I originally referred to is no longer there and I didn't manage my branch too carefully. Sorry!

**Pull request closed without merging**
