### PR TITLE
Update day1-afternoon.qmd

### PR DESCRIPTION
**Pull request by ryantibs**

### CODE REVIEW

**Comment by ryantibs** [comment]
@XuedaShen Please add sanity check of `nowcaster()` function so that it repoduces your previous one-day calculation

**Comment by ryantibs** [comment]
@XuedaShen Please don't redefine `nowcaster()`, please just remind them

Also, let's make the nowcasts extend back to start-of-time + window_length

**Comment by ryantibs** [comment]
@XuedaShen @dajmcdon Figure aesthetics on 86 and 87 may need some work. 

Let's use lines and note dots-and-line?

**Comment by XuedaShen** [comment]
ALL DONE.

`epix_slide()` sanity check:

image

People are reminded of how we call `epix_slide()` after introducing subtleties on `.all_versions`
image


Revised nowcasts visualization: 
image

image

**Comment by ryantibs** [comment]
@XuedaShen Nice job! 

One Q: Are you using from Dan's set of "approved colors"?

**Comment by ryantibs** [comment]
You can use `scale_color_delphi()`

**Comment by XuedaShen** [comment]
@ryantibs I wasn't able to find `scale_color_delphi()`. Instead used `scale_color_viridis` with same options as in other plots:

image
image

**Comment by XuedaShen** [comment]
Finally got it

image
image

**Comment by ryantibs** [comment]
Dor some reason Xueda's last few commits introduced some conflicts but I believe I resolved the merge conflicts (also added the provisional data to the smoothed nowcast figure). Will go and merge

**Pull request merged**
